FROM node:20 AS builder
COPY package*.json ./
# don't install dev dependencies for the docker image
RUN npm install --omit=dev

FROM node:20-alpine AS app
WORKDIR /app
RUN mkdir -p /app/data && chown -R node:node /app/data

RUN apk update && \
  # wrap process in --init in order to handle kernel signals
  # https://github.com/krallin/tini#using-tini
  apk add --no-cache tini && \
  rm -rf /var/cache/apk/*

RUN npm install -g nodemon
COPY --from=builder node_modules node_modules/
RUN chown -R node:node /app/node_modules/speedtest-net
COPY package*.json ./
COPY index.js index.js
COPY src ./src

USER node
ENTRYPOINT ["/sbin/tini", "--"]
CMD [ "nodemon", "./index.js" ]
